name: Vocanta
favicon: null
layout_spectrum: 0.2706
typography_spectrum: 0.89271
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e32c3b'
    - '#606060'
    - '#000000'
    - '#ffca27'
    - '#2eb21a'
  brandStrength: 0.8251492185518146
  lightness: 0.8432770604267716
  saturation: 0.4302730215713382
  rhythmicContrast: 0.5101301718968898
purpose: []
